docs(README): update to use combineReducers from redux-immutable
americanexpress/iguazu-rpc pull request #13
Opened 2020-05-04 20:22 UTC by brantmullinix

2020-05-04 20:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/americanexpress/iguazu-rpc?pullRequest=13) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/americanexpress/iguazu-rpc?pullRequest=13) before we can accept your contribution.<br/><hr/>**Brant Mullinix** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/americanexpress/iguazu-rpc?pullRequest=13) it.</sub>

2020-05-04 20:41 UTC, mtomcal commented
Thanks @brantmullinix for your contribution! What about supporting older implementations that did not rely on completely immutable state? We need to be careful to show the v5 way and the previous v4 way in our documentation. Also would you add a brief PR description?

2020-05-04 20:41 UTC, mtomcal requested changes
See previous comment.

2020-05-04 20:44 UTC, brantmullinix commented
> Thanks @brantmullinix for your contribution! What about supporting older implementations that did not rely on completely immutable state? We need to be careful to show the v5 way and the previous v4 way in our documentation. Also would you add a brief PR description?

@mtomcal The open source version v5 is completely immutable and in v4 isn't the reducer added in axp-root already?

2020-05-04 21:13 UTC, mtomcal commented
Talked offline about this. This looks good as is.

2020-05-04 21:15 UTC, mtomcal reviewed
Also, please sign the CLA and make sure the build passes. I think the commit message scope doesnt not allow for all capitals. `docs(readme): update to use combineReducers from redux-immutable`

2020-05-05 02:57 UTC, brantmullinix commented
> Also, please sign the CLA and make sure the build passes. I think the commit message scope doesnt not allow for all capitals. `docs(readme): update to use combineReducers from redux-immutable`

@mtomcal Resolved both.

2020-05-05 12:56 UTC, marcusrbrown approved these changes

2020-05-05 21:40 UTC, mtomcal approved these changes

2020-05-05 21:40 UTC, merged