chore(contributing): update contributor guidelines
americanexpress/iguazu-rpc pull request #4
Opened 2020-01-23 14:59 UTC by nellyk

2020-01-23 20:23 UTC, mtomcal submitted a review, later dismissed

2020-01-24 03:43 UTC, anescobar1991 requested changes

2020-01-24 03:43 UTC, anescobar1991 commented on CONTRIBUTING.md
> +4. You can now run any of this scripts from the root folder.
`this` should be `these`.

2020-01-24 21:42 UTC, 10xLaCroixDrinker submitted a review, later dismissed

2020-02-05 18:05 UTC, 10xLaCroixDrinker requested changes

2020-02-05 18:05 UTC, 10xLaCroixDrinker commented on CONTRIBUTING.md
> +    $ cd npm install
```suggestion
    $ npm install
```

2020-02-05 18:07 UTC, 10xLaCroixDrinker requested changes

2020-02-05 18:07 UTC, 10xLaCroixDrinker commented on CONTRIBUTING.md
> +When submitting a new feature request or enhancement of an existing feature please review the following:-
```suggestion
When submitting a new feature request or enhancement of an existing feature please review the following:
```

2020-02-07 22:05 UTC, 10xLaCroixDrinker submitted a review, later dismissed

2020-02-19 19:56 UTC, Francois-Esquire requested changes

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +Add any other context or screenshots or animated GIFs about the feature request
```suggestion
Add any other context or screenshots or animated GIFs about the feature request.
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +Steps to reproduce the behavior, please provide code snippets or a link to repository
```suggestion
Please provide code snippets or a link to repository with steps to reproduce the behavior.
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +Please provide a description of the expected behavior
```suggestion
Please provide a description of the expected behavior.
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +We follow [conventional commits](https://www.conventionalcommits.org/) for git commit message formatting. These rules make it easier to review commit logs and improve contextual understanding of code
Breaking line length:

```suggestion
We follow [conventional commits](https://www.conventionalcommits.org/)
for git commit message formatting. These rules make it easier to review
commit logs and improve contextual understanding of code changes.
This also allows us to auto-generate the `CHANGELOG` from commit messages.
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +2. Afterwards run the following commands in your terminal
The other pointers are using grammatical breaks (`.`, eg), would make sense to do that with all the points.

```suggestion
2. Afterwards run the following commands in your terminal:
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +3. Install the dependencies by running
```suggestion
3. Install the dependencies by running:
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +    $  npm install
```suggestion
    $ npm install
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +Runs linting on the current branch, checks that the commits follow [conventional commits](https://www.conventionalcommits.org/) and verifies that the `package-lock.json` file includes public NPM regi
```suggestion
Runs linting on the current branch, checks that the commits follow
[conventional commits](https://www.conventionalcommits.org/) and
verifies that the `package-lock.json` file includes public NPM registry URLs.
```

2020-02-19 19:56 UTC, Francois-Esquire commented on CONTRIBUTING.md
> +### Security Bugs
```suggestion
### Security bugs
```

2020-02-19 19:58 UTC, Francois-Esquire commented
Added a few suggestions, mostly grammatical and for staying consistent amongst the document. Otherwise looks solid.

2020-02-20 14:27 UTC, nellyk commented
Thank you for the detailed review 

> Added a few suggestions, mostly grammatical and for staying consistent within the document. Otherwise looks solid.

2020-02-20 17:09 UTC, Francois-Esquire approved these changes

2020-02-20 21:06 UTC, mtomcal approved these changes

2020-02-24 15:51 UTC, 10xLaCroixDrinker approved these changes

2020-02-25 18:31 UTC, anescobar1991 approved these changes

2020-02-25 20:43 UTC, merged